pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                // Clone your GitHub repo
                git 'https://github.com/Prak1701/p54.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                // Build containers using docker-compose
                sh 'docker-compose build'
            }
        }

        stage('Run Docker Containers') {
            steps {
                // Run containers in detached mode
                sh 'docker-compose up -d'
            }
        }
    }
}
